version: "3.1"
services:
  es:
    hostname: es
    image: huawei-harbor.aksoinfo.com/akso/es6.7.1:20230523142009
    restart: always
    volumes:
      - D:\Volumes\es:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - 9200:9200
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp
  kibana:
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:6.7.1
    restart: always
    volumes:
      - D:\Volumes\kibana:/var/lib/kibana
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.8.19-management
    restart: always
    volumes:
      - D:\Volumes\rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=akso
    ports:
      - "15672:15672"
      - "5672:5672"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp
  redis:
    hostname: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp
  nacos:
    hostname: nacos
    restart: always
    image: huawei-harbor.aksoinfo.com/akso/nacos:2.1.0
    volumes:
      - D:\Volumes\nacos:/home/nacos/data
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
    ports:
      - "8848:8848"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp
  pgsql:
    hostname: pgsql
    restart: always
    image: huawei-harbor.aksoinfo.com/akso/pgsql:14.8
    volumes:
      - D:\Volumes\postgresql:/bitnami/postgresql
    environment:
      # - MODE=standalone
      - POSTGRES_PASSWORD=Eqms123456
      - POSTGRESQL_VOLUME_DIR=/bitnami/postgresql
      - PGDATA=/bitnami/postgresql/data
      - POSTGRESQL_ENABLE_LDAP=no
      - POSTGRESQL_ENABLE_TLS=no
      - POSTGRESQL_LOG_HOSTNAME=false
      - POSTGRESQL_PGAUDIT_LOG_CATALOG=off
      - POSTGRESQL_CLIENT_MIN_MESSAGES=error
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=pgaudit
      - POSTGRESQL_LOG_DESTINATION=syslog
      - POSTGRESQL_LOG_COLLECTOR=on
      - POSTGRESQL_LOG_DIRECTORY=/bitnami/postgresql/logs
      - POSTGRESQL_LOG_FILENAME=postgresql-%Y-%m-%d_%H%M%S.log
      - POSTGRESQL_LOG_ROTATION_AGE=7d
      - POSTGRESQL_LOG_ROTATION_SIZE=100MB
      - POSTGRESQL_LOG_MIN_MESSAGES=info
      - POSTGRESQL_LOG_MIN_DURATION_STATEMENT=1000
      - POSTGRESQL_LOG_CHECKPOINTS=on
      - POSTGRESQL_LOG_CONNECTIONS=on
      - POSTGRESQL_LOG_DISCONNECTIONS=on
      - POSTGRESQL_LOG_DURATION=on
      - POSTGRESQL_LOG_LINE_PREFIX=%m
      - POSTGRESQL_LOG_LOCK_WAITS=on
      - POSTGRESQL_LOG_STATEMENT=ddl
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp
  seq:
    hostname: seq
    restart: always
    image: huawei-harbor.aksoinfo.com/akso/seq:2022
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=FIAUI49F697ZQKhb1PgK9QOzgUKZOPL4ZRWZFr7ENile0q8QYA== #seq初始化密码123456
      - SEQ_FIRSTRUN_REQUIREAUTHTENTICATIONFORHTTPINGESTION=True
    ports:
      - 5341:5341
      - 8000:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp
  partainer:
    hostname: partainer
    restart: always
    image: portainer/portainer-ce:2.5.1
    ports:
      - 5342:5342
      - 9000:9000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - egmp  
networks:
  egmp:
